// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package buffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldMetrics struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldMetrics(buf []byte, offset flatbuffers.UOffsetT) *FieldMetrics {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldMetrics{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldMetricsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldMetrics(buf []byte, offset flatbuffers.UOffsetT) *FieldMetrics {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldMetrics{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldMetricsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldMetrics) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldMetrics) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldMetrics) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FieldMetrics) Size() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldMetrics) MutateSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *FieldMetrics) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldMetrics) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func FieldMetricsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FieldMetricsAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func FieldMetricsAddSize(builder *flatbuffers.Builder, size int32) {
	builder.PrependInt32Slot(1, size, 0)
}
func FieldMetricsAddLength(builder *flatbuffers.Builder, length int32) {
	builder.PrependInt32Slot(2, length, 0)
}
func FieldMetricsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
