// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package buffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldEntry(buf []byte, offset flatbuffers.UOffsetT) *FieldEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldEntry(buf []byte, offset flatbuffers.UOffsetT) *FieldEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldEntry) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FieldEntry) Value(obj *Field) *Field {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Field)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func FieldEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FieldEntryAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func FieldEntryAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func FieldEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
