// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package buffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldMetrix struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldMetrix(buf []byte, offset flatbuffers.UOffsetT) *FieldMetrix {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldMetrix{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldMetrixBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldMetrix(buf []byte, offset flatbuffers.UOffsetT) *FieldMetrix {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldMetrix{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldMetrixBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldMetrix) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldMetrix) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldMetrix) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FieldMetrix) Size() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldMetrix) MutateSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *FieldMetrix) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldMetrix) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func FieldMetrixStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FieldMetrixAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func FieldMetrixAddSize(builder *flatbuffers.Builder, size int32) {
	builder.PrependInt32Slot(1, size, 0)
}
func FieldMetrixAddLength(builder *flatbuffers.Builder, length int32) {
	builder.PrependInt32Slot(2, length, 0)
}
func FieldMetrixEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
