// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package buffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RootFieldTerm struct {
	_tab flatbuffers.Table
}

func GetRootAsRootFieldTerm(buf []byte, offset flatbuffers.UOffsetT) *RootFieldTerm {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RootFieldTerm{}
	x.Init(buf, n+offset)
	return x
}

func FinishRootFieldTermBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRootFieldTerm(buf []byte, offset flatbuffers.UOffsetT) *RootFieldTerm {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RootFieldTerm{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRootFieldTermBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RootFieldTerm) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RootFieldTerm) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RootFieldTerm) Entries(obj *FieldTerm, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RootFieldTerm) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RootFieldTermStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RootFieldTermAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func RootFieldTermStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RootFieldTermEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
