// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package buffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TermFrequency struct {
	_tab flatbuffers.Table
}

func GetRootAsTermFrequency(buf []byte, offset flatbuffers.UOffsetT) *TermFrequency {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TermFrequency{}
	x.Init(buf, n+offset)
	return x
}

func FinishTermFrequencyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTermFrequency(buf []byte, offset flatbuffers.UOffsetT) *TermFrequency {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TermFrequency{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTermFrequencyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TermFrequency) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TermFrequency) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TermFrequency) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TermFrequency) Value() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TermFrequency) MutateValue(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func TermFrequencyStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TermFrequencyAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func TermFrequencyAddValue(builder *flatbuffers.Builder, value int32) {
	builder.PrependInt32Slot(1, value, 0)
}
func TermFrequencyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
